#+TITLE: Bag-of-Words extended example - Delta Airline Tweets
#+AUTHOR: [yourname]
#+SUBTITLE: In-class practice
#+STARTUP:overview hideblocks indent
#+OPTIONS: toc:nil num:nil ^:nil
#+PROPERTY: header-args:R :session *R* :results output :exports both :noweb yes
* README

This file covers the Delta airline tweet example from the introductory
lecture on text mining with Bag-of-Words:
- Getting the data
- String manipulation

Most of this material can be found in Kwartler, Text mining in
practice with R (Wiley, 2019). Solutions are on GitHub as PDF files.

* TODO Identify and pledge yourself

1) In Emacs, replace the placeholder ~[yourname]~ at the top of this
   file by your own name and write ~(pledged)~ next to it
2) Go with the cursor on the headline and hange the ~TODO~ label to ~DONE~
   by entering ~S-<right>~ ("Shift + right-arrow").
* TODO Setting up the R environment

1) Open a command line terminal (enter ~CMD~ in the search field)
2) Enter ~R~ at the prompt to start an R terminal (or shell)
3) Install three packages: ~stringi~, ~stringr~ and ~qdap~ with the
   following commands:
   #+begin_example R
    install.packages("stringi")
    install.packages("stringr")
    install.packages("qdap")
  #+end_example

* TODO Getting the data

* TODO String manipulation I

* TODO String manipulation II

* TODO Wow! Congratulations!

Well done! You've reached the end of the first in-class practice file.

If you've completed all steps, you can now upload the Org-mode file to
Canvas (see ~Assignments > In-class practice~.
