#+TITLE: CSC 105 Digital Humanities - Spring 2023 Syllabus
#+AUTHOR: Marcus Birkenkrahe
#+options: toc:nil
#+startup: overview
* General Course Information

- Meeting Times: Tue/Thu from 2.30 - 3.45 pm
- Meeting place: Derby science building computer lab 209
- Professor: Marcus Birkenkrahe
- Office: Derby Science Building 210
- Phone: (870) 307-7254 (Office) / (501 422-4725 (Private)
- Office Hours: Tue/Thu 4-4.30 pm, Mon/Wed/Fri 4.15-4.45 pm
- Textbooks: Text mining in Practice with R (Kwartler, 2017), Text
  mining with R - A Tidy Approach (Silge/Robinson, 2017)
- Lesson plan: follows "Text mining with R" track in DataCamp
  
* Objectives

Understanding and practicing the basis of current AI technologies used
in Natural Language Processing applications like DALL-E, ChatGPT,
Alexa or Siri. Applying text mining techniques to sentiment analysis,
word association, and pattern matching.

* Student learning outcomes

Students who complete CSC 105, "Digital Humanities - working with
text data", will be able to:

- Wrangle, visualize and model text data analysis problems
- Manipulate string data with the ~stringr~ R package
- Mine text data with the Bag-of-Words technique
- Carry out simple sentiment analysis of text data
- Know how to effectively present assignment results
- Complete an independent research project and present results
- Master data science infrastructure for editing and graphing

* Course requirements

None. Some basic proficiency in R and the "Tidyverse" packages is
useful but not required (use DataCamp lessons or Matloff's "fasteR"
online tutorial on GitHub).

Some knowledge of, and experience with computers is useful but not
critical. Curiosity and discipline are essential. You will gain
data literacy skills by taking this course. The course will prepare
you for further studies in computer and data science, or in other
disciplines that use modern computing, i.e. every discipline, from
accounting to zoology).

* Grading system

| REQUIREMENT           | UNITS | PPU | TOTAL | % of TOTAL |
|-----------------------+-------+-----+-------+------------|
| Final exam            |     1 | 100 |   100 |        20. |
| Home assignments      |    15 |  10 |   150 |        30. |
| Class assignments     |    10 |  10 |   100 |        20. |
| Final project         |     1 |  50 |    50 |        10. |
| Multiple-choice tests |    10 |  10 |   100 |        20. |
|-----------------------+-------+-----+-------+------------|
| TOTAL                 |       |     |   500 |       100. |
|-----------------------+-------+-----+-------+------------|
#+TBLFM: @2$4=$2*$3::@2$5=(@2$4/@7$4)*100::@3$4=$2*$3::@3$5=(@3$4/@7$4)*100::@4$4=$2*$3::@4$5=(@4$4/@7$4)*100::@5$4=$2*$3::@5$5=(@5$4/@7$4)*100::@6$5=(@6$4/@7$4)*100::@7$4=vsum(@2..@6)::@7$5=vsum(@2..@6)

You should be able to see your current grade at any time using the
Schoology gradebook for the course.

* Grading table

This table is used to convert completion rates into letter grades. for
the midterm results, letter grades still carry signs, while for the
term results, only straight letters are given (by rounding up).

|--------+---------------+---------------|
|      *%* | *MIDTERM GRADE* | *FINAL GRADE*   |
|--------+---------------+---------------|
| 100-98 | A+            |               |
|  97-96 | A             | A (PASSED -   |
|  95-90 | A-            | VERY GOOD)    |
|--------+---------------+---------------|
|  89-86 | B+            |               |
|  85-80 | B             | B (PASSED -   |
|  79-76 | B-            | GOOD)         |
|--------+---------------+---------------|
|  75-70 | C+            |               |
|  69-66 | C             | C (PASSED -   |
|  65-60 | C-            | SATISFACTORY) |
|--------+---------------+---------------|
|  59-56 | D+            |               |
|  55-50 | D             | D (PASSED)    |
|--------+---------------+---------------|
|   49-0 | F             | F (FAILED)    |
|--------+---------------+---------------|
* Standard Policies
** Honor Code

All graded work in this class is to be pledged in accordance with the
Lyon College Honor Code. The use of a phone for any reason during the
course of an exam is considered an honor code violation.

** Class Attendance Policy

Students are expected to attend all class periods for the courses in
which they are enrolled. They are responsible for conferring with
individual professors regarding any missed assignments. Faculty
members are to notify the Registrar when a student misses the
equivalent of one, two, three, and four weeks of class periods in a
single course. Under this policy, there is no distinction between
“excused” and “unexcused” absences, except that a student may make up
work missed during an excused absence. A reminder of the college’s
attendance policy will be issued to the student at one week, a second
reminder at two weeks, a warning at three weeks, and notification of
administrative withdrawal and the assigning of an “F” grade at four
weeks. Students who are administratively withdrawn from more than one
course will be placed on probation or suspended.

** Academic Support

The Morrow Academic Center (MAC) helps students who want to improve
grades by providing peer-led services including Supplemental
Instruction (SI), tutoring, the Writing Center, and academic coaching
as well providing 24-hour, online tutoring for all subjects through
Tutor.com. A schedule of peer-led services is available at
lyon.edu/mac and Tutor.com is accessed through courses in
Schoology. Contact Donald Taylor, Director of Academic Support, at
870-307-7319 or donald.taylor@lyon.edu for more information about MAC
services.

** Technology Support

For general technology support, you can contact the IT department by
emailing support@lyon.edu or by calling 870-307-7555. For assistance
with classroom-related technologies, such as the learning management
system (LMS), you can request support using the methods above, or you
can contact sarah.williams@lyon.edu directly for assistance. Your
course content will be accessible digitally using either the Schoology
or Canvas LMS. Both LMS platforms will use your myLyon credentials for
your student login.

- For Canvas, login at lyon.instructure.com
- For Schoology, login at lyon.schoology.com

** Disabilities

Students seeking reasonable accommodations based on documented
learning disabilities must contact Interim Director of Academic
Support Donald Taylor in the Morrow Academic Center at (870) 307-7019
or at donald.taylor@lyon.edu.

** Harassment, Discrimination, and Sexual Misconduct

Lyon College seeks to provide all members of the community with a safe
and secure learning and work environment that is free of crime and/or
policy violations motivated by discrimination, sexual and bias-related
harassment, and other violations of rights. The College has a
zero-tolerance policy against gender-based misconduct, sexual assault,
and interpersonal violence toward any member or guest of the Lyon
College community. Any individual who has been the victim of an act of
violence or intimidation is urged to make an official report by
contacting a campus Title IX coordinator or by visiting
www.lyon.edu/file-a-title-ix-report. A report of an act of violence or
intimidation will be dealt with promptly. Confidentiality will be
maintained to the greatest extent possible within the constraints of
the law. For more information regarding the College’s Title IX
policies and procedures, visit www.lyon.edu/title-ix.

** Mental & Behavioral Health

Lyon College is dedicated to ensuring each student has access to
mental and behavioral health resources. The College’s Mental and
Behavioral Health Office is located in Edwards Commons and is
partnered with White River Health System’s Behavioral Health
Clinic. The office is committed to helping the Lyon community achieve
maximum mental and behavioral wellness through both preventative and
reactive care. A full-time, licensed, professional counselor provides
counseling, consultations, outreach, workshops, and many more mental
and behavioral services to Lyon students, faculty, and staff at no
cost. The Mental and Behavioral Health Office also provides access to
White River Health System’s services and facilities, including
medication management and in-patient and out-patient care. To make an
appointment, contact counseling@lyon.edu.

** College-Wide COVID-19 Policies

The College does not require masks in instructional and meeting spaces
inside academic buildings. However, if instructors require masks in
their classroom, lab, or studio, then students and guests must comply
with that requirement.  Vaccines are strongly encouraged for all
faculty, staff, and students. Vaccines are not mandated for Lyon
College community members, although there may be specific courses
involving interactions with vulnerable, external populations where a
vaccine may be required.  The College will continue to offer
symptomatic testing for students, faculty and staff.

** Details

Details specific to this course may be found in the subsequent pages
of this syllabus. Those details will include at least the following:
- A description of the course consistent with the Lyon College
  catalog.
- A list of student learning outcomes for the course.
- A summary of all course requirements.
- An explanation of the grading system to be used in the course.
- Any course-specific attendance policies that go beyond the College
  policy.
- Details about what constitutes acceptable and unacceptable student
  collaboration on graded work.
- A clear statement about which LMS is being used for the course.

** Learning Management System (LMS)

We will use Canvas in this course.
** Assignments and Honor Code

There will be several assignments during the summer school,
including programming assignments and multiple-choice tests. They
are due at the beginning of the class period on the due date. Once
class begins, the assigment will be considered one day late if it
has not been turned in.  Late programs will not be accepted without
an extension. Extensions will *not* be granted for reasons such as:

- You could not get to a computer
- You could not get a computer to do what you wanted it to do
- The network was down
- The printer was out of paper or toner
- You erased your files, lost your homework, or misplaced your
  flash drive
- You had other coursework or family commitments that interfered
  with your work in this course

Put “Pledged” and a note of any collaboration in the comments of any
program you turn in. Programming assignments are individual efforts,
but you may seek assistance from another student or the course
instructor.  You may not copy someone else’s solution. If you are
having trouble finishing an assignment, it is far better to do your
own work and receive a low score than to go through an honor trial and
suffer the penalties that may be involved.

What is cheating on an assignment? Here are a few examples:

- Having someone else write your assignment, in whole or in part
- Copying an assignment someone else wrote, in whole or in part
- Collaborating with someone else to the extent that your
  submissions are identifiably very similar, in whole or in part
- Turning in a submission with the wrong name on it

What is not cheating?  Here are some examples:
- Talking to someone in general terms about concepts involved in an
  assignment
- Asking someone for help with a specific error message or bug in
  your program
- Getting help with the specifics of language syntax or citation
  style
- Utilizing information given to you by the instructor

Any assistance must be clearly explained in the comments at the
beginning of your submission.  If you have any questions about this,
please ask or review the policies relating to the Honor Code.

Absences on Days of Exams: Test “make-ups” will only be allowed if
arrangements have been made prior to the scheduled time.  If you are
sick the day of the test, please e-mail me or leave a message on my
phone before the scheduled time, and we can make arrangements when
you return.

** Attendance policy

In accordance with college policy, if you miss 4 weeks of class, you
fail the course automatically. Any missed meetings result in an [[https://catalog.lyon.edu/class-attendance]["Early
Alert" report]].

You should take care not to miss consecutive sessions if at all
possible - otherwise you risk losing touch with the class and falling
behind.
* Important Dates

| DATE           | DAY              | DESCRIPTION                                 |
|----------------+------------------+---------------------------------------------|
| 3 January      | Tuesday          | Last day to deposit for '22 spring semester |
| 10 January     | Tuesday          | Classes begin                               |
| 16 January     | Monday           | MLK Day - no classes                        |
| 17 January     | Tuesday          | Last day to add a class                     |
| 24 January     | Tuesday          | Last day to drop without record of course   |
|                |                  | Last day to declare a course pass-fail      |
|                |                  | Deadline for removal of incompletes         |
| 25-28 February | Saturday-Tuesday | Mental-Health break (no classes)            |
| 1 March        | Wednesday        | Mid-term grades available by noon           |
| 8 March        | Wednesday        | Lst day to drop a course with a "W"         |
| 18-26 March    | Saturday-Sunday  | Spring break                                |
| 7-9 April      | Friday-Sunday    | Easter break                                |
| 18 April       | Tuesday          | Honors Convocation                          |
| 4 May          | Wednesday        | Last day of spring classes                  |
| 4-7 May        | Thursday-Sunday  | Final exams for graduating seniors          |
|                |                  | (start 6pm Thu, no exams before 1pm Sun)    |
| 5-10 May       | Thursday-Tuesday | Final exams for non-graduating students     |
|                |                  | (no exams before 1pm on Sunday)             |
| 9 May          | Tuesday          | Senior grades due by noon                   |
| 12 May         | Friday           | Baccalaureate                               |
| 13 May         | Saturday         | Spring commencement                         |
| 17 May         | Wednesday        | All final grades due by noon                |

* Schedule and session content

For this course, we use the DataCamp track "[[https://app.datacamp.com/learn/skill-tracks/text-mining-with-r][Text mining with R]]". Only
a couple of courses are missing. If you complete them, too, you will
emerge from this class with four text mining certificates.

| WEEK | DATE          | DATACAMP ASSIGNMENT              | TESTS   |
|------+---------------+----------------------------------+---------|
|    1 | Jan 10,12     |                                  |         |
|------+---------------+----------------------------------+---------|
|    2 | Jan 17,19     | Wrangling text                   | Test 1  |
|------+---------------+----------------------------------+---------|
|    3 | Jan 24,26     | Visualizing text                 | Test 2  |
|------+---------------+----------------------------------+---------|
|    4 | Jan 31, Feb 2 | Sentiment analysis               | Test 3  |
|------+---------------+----------------------------------+---------|
|    5 | Feb 7,9       | String basics                    |         |
|------+---------------+----------------------------------+---------|
|    6 | Feb 14,16     | Introduction to ~stringr~          | Test 4  |
|------+---------------+----------------------------------+---------|
|    7 | Feb 21,23     | Pattern matching with regexp     | Test 5  |
|------+---------------+----------------------------------+---------|
|    8 | Mar 2         | More advanced matching           | Test 6  |
|------+---------------+----------------------------------+---------|
|    9 | Mar 7,9       | Three case studies               |         |
|------+---------------+----------------------------------+---------|
|   10 | Mar 14,16     | Text mining with Bag-of-Words    | Test 7  |
|------+---------------+----------------------------------+---------|
|   11 | Mar 28,30     | Word clouds and other visuals    | Test 8  |
|------+---------------+----------------------------------+---------|
|   12 | Apr 4,6       | Word clustering and tokenization | Test 9  |
|------+---------------+----------------------------------+---------|
|   13 | Apr 11,13     | HR analytics case study          |         |
|------+---------------+----------------------------------+---------|
|   14 | Apr 18,20     | Polarity scoring                 | Test 10 |
|------+---------------+----------------------------------+---------|
|   15 | Apr 25,27     | Visualizing sentiment            |         |
|------+---------------+----------------------------------+---------|
|   16 | May 2         | Case study: Airbnb reviews       |         |
|------+---------------+----------------------------------+---------|
